baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Go-adc'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
